import express from 'express';
import { authenticate } from '../../middleware/authenticate.js';
import { authorize } from '../../middleware/authorize.js';
import { ROLES } from '../../config/rolePermissions.js';

const router = express.Router();

// Get FAQ data
router.get('/faq', authenticate, async (req, res) => {
  try {
    // This would typically come from database
    const faqData = [
      {
        id: 1,
        category: 'Leave Management',
        question: 'How do I apply for leave?',
        answer: 'To apply for leave, go to the Leave section in your dashboard, click "Apply for Leave", fill in the required details including dates, leave type, and reason, then submit for approval.',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 2,
        category: 'Attendance',
        question: 'What should I do if I forgot to clock in/out?',
        answer: 'If you forgot to clock in or out, you can submit an attendance correction request through the Attendance section. Your manager will need to approve the correction.',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 3,
        category: 'Payroll',
        question: 'When will my payslip be available?',
        answer: 'Payslips are typically generated by the 5th of each month for the previous month. You will receive a notification when your payslip is ready for download.',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 4,
        category: 'Profile',
        question: 'How do I update my personal information?',
        answer: 'You can update your personal information by going to your Profile section. Some changes may require HR approval, such as contact details or emergency contacts.',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 5,
        category: 'System',
        question: 'I\'m having trouble logging in. What should I do?',
        answer: 'If you\'re having login issues, first try resetting your password. If the problem persists, contact IT support or your HR department for assistance.',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 6,
        category: 'Documents',
        question: 'How do I upload required documents?',
        answer: 'Go to the Documents section in your profile, select the document type, and upload the file. Ensure the file is in PDF or image format and under 5MB.',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ];

    res.json({
      success: true,
      data: faqData,
      message: 'FAQ data retrieved successfully'
    });
  } catch (error) {
    console.error('Error fetching FAQ data:', error);
    res.status(500).json({
      success: false,
      error: {
        code: 'INTERNAL_SERVER_ERROR',
        message: 'Failed to fetch FAQ data'
      }
    });
  }
});

// Submit support ticket
router.post('/support-ticket', authenticate, async (req, res) => {
  try {
    const { subject, category, priority, description } = req.body;
    const userId = req.user.id;

    // Validate required fields
    if (!subject || !description) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'VALIDATION_ERROR',
          message: 'Subject and description are required'
        }
      });
    }

    // In a real implementation, this would save to database
    const supportTicket = {
      id: Date.now(), // Mock ID
      userId,
      subject,
      category: category || 'general',
      priority: priority || 'medium',
      description,
      status: 'open',
      createdAt: new Date(),
      updatedAt: new Date()
    };

    // Here you would typically:
    // 1. Save to database
    // 2. Send email notification to support team
    // 3. Create audit log entry

    res.status(201).json({
      success: true,
      data: supportTicket,
      message: 'Support ticket submitted successfully'
    });
  } catch (error) {
    console.error('Error submitting support ticket:', error);
    res.status(500).json({
      success: false,
      error: {
        code: 'INTERNAL_SERVER_ERROR',
        message: 'Failed to submit support ticket'
      }
    });
  }
});

// Get help resources
router.get('/resources', authenticate, async (req, res) => {
  try {
    const resources = [
      {
        id: 1,
        title: 'Employee Handbook',
        description: 'Complete guide to company policies and procedures',
        type: 'download',
        url: '/api/documents/employee-handbook.pdf',
        category: 'documentation',
        isActive: true
      },
      {
        id: 2,
        title: 'Video Tutorials',
        description: 'Step-by-step video guides for common tasks',
        type: 'external',
        url: 'https://help.company.com/videos',
        category: 'tutorials',
        isActive: true
      },
      {
        id: 3,
        title: 'System Status',
        description: 'Check current system status and maintenance schedules',
        type: 'external',
        url: 'https://status.company.com',
        category: 'system',
        isActive: true
      },
      {
        id: 4,
        title: 'Policy Documents',
        description: 'Access all company policies and guidelines',
        type: 'internal',
        url: '/hr/policies',
        category: 'policies',
        isActive: true
      }
    ];

    res.json({
      success: true,
      data: resources,
      message: 'Help resources retrieved successfully'
    });
  } catch (error) {
    console.error('Error fetching help resources:', error);
    res.status(500).json({
      success: false,
      error: {
        code: 'INTERNAL_SERVER_ERROR',
        message: 'Failed to fetch help resources'
      }
    });
  }
});

// Get contact information
router.get('/contact-info', authenticate, async (req, res) => {
  try {
    const contactInfo = [
      {
        id: 1,
        type: 'HR Department',
        contact: 'hr@company.com',
        hours: 'Mon-Fri, 9:00 AM - 6:00 PM',
        isActive: true
      },
      {
        id: 2,
        type: 'IT Support',
        contact: '+1 (555) 123-4567',
        hours: 'Mon-Fri, 8:00 AM - 8:00 PM',
        isActive: true
      },
      {
        id: 3,
        type: 'Emergency Contact',
        contact: '+1 (555) 999-0000',
        hours: '24/7 Available',
        isActive: true
      }
    ];

    res.json({
      success: true,
      data: contactInfo,
      message: 'Contact information retrieved successfully'
    });
  } catch (error) {
    console.error('Error fetching contact info:', error);
    res.status(500).json({
      success: false,
      error: {
        code: 'INTERNAL_SERVER_ERROR',
        message: 'Failed to fetch contact information'
      }
    });
  }
});

export default router;